# Generated by Django 4.2.4 on 2023-08-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
        ('catalog', '0004_alter_book_genre_alter_book_isbn_alter_book_summary_and_more'),
    ]

    operations = [
    ]
