# Generated by Django 4.2.4 on 2023-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_genre_alter_book_isbn_alter_book_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
